import React from "react";

import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ViewStyle,
} from "react-native";

type Props = {
  onSelect?: () => void;
  style?: ViewStyle;
};

const AIDocumentPlanCard: React.FC<Props> = ({ onSelect, style }) => {
  return (
    <View style={[styles.card, style]}>
      <Text style={styles.planTitle}>AI-Document</Text>
      <Text style={styles.price}>$49</Text>

      <Text style={styles.subHeader}>
        Access your AI-drafted document. Use our AI to edit it or download it
        for your finalization.
      </Text>

      <TouchableOpacity style={styles.buttonOutline} onPress={onSelect}>
        <Text style={styles.buttonOutlineText}>Access Document</Text>
      </TouchableOpacity>

      <View style={styles.featureList}>
        <Text style={styles.feature}>
          ✅ Document generated by the world&apos;s most popular lawyer-tuned AI
          for self help.
        </Text>
        <Text style={styles.feature}>
          ✅ Use the Inhouse AI to suggest edits for your document for up to 24
          hours.
        </Text>
        <Text style={styles.feature}>
          ✅ Download in a format that works for you: Word or PDF.
        </Text>
        <Text style={styles.warning}>
          ⚠ Disclaimer – AI generated documents are for educational and
          informational purposes only and are not legal advice. Always consult a
          licensed attorney about your specific legal matter.
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  card: {
    flex: 1,
    minWidth: 260,
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 10,
  },
  planTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
    marginBottom: 4,
  },
  price: {
    fontSize: 30,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 12,
  },
  subHeader: {
    fontSize: 13,
    color: "#111827",
    marginBottom: 18,
  },
  buttonOutline: {
    borderWidth: 1,
    borderColor: "#1B2B48",
    paddingVertical: 12,
    borderRadius: 999,
    marginBottom: 18,
  },
  buttonOutlineText: {
    textAlign: "center",
    color: "#1B2B48",
    fontSize: 14,
    fontWeight: "600",
  },
  featureList: {
    gap: 8,
  },
  feature: {
    fontSize: 13,
    color: "#1B2B48",
    lineHeight: 18,
  },
  warning: {
    fontSize: 13,
    color: "#CA8A04",
    marginTop: 8,
    lineHeight: 16,
  },
});

export default AIDocumentPlanCard;
